# PRODUCTION
version: "3"

services:
  calendar.marcostevanon.ovh:
    container_name: calendar.marcostevanon.ovh
    image: node:10-alpine
    build: .
    restart: always
    labels:
      - "traefik.frontend.rule=Host:calendar.marcostevanon.ovh"
      - "traefik.port=1883"
      - "traefik.enable=true"
    command: npm run prod
    networks:
      - traefik

networks:
  traefik:
    external: true