# DEVELOPMENT
version: "3"

services:
  dev.api.calendar.marcostevanon.ovh:
    container_name: dev.api.calendar.marcostevanon.ovh
    image: registry.gitlab.com/calendar-app/api:dev
    restart: always
    labels:
      - "traefik.frontend.rule=Host:dev.api.calendar.marcostevanon.ovh"
      - "traefik.port=1883"
      - "traefik.enable=true"
    env_file:
      - .env
    command: npm run prod
    networks:
      - traefik

networks:
  traefik:
    external: true